from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(939, 531)
        font = QtGui.QFont()
        font.setPointSize(15)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.loadBtn = QtWidgets.QPushButton(self.centralwidget)
        self.loadBtn.setGeometry(QtCore.QRect(20, 70, 271, 51))
        self.loadBtn.setObjectName("loadBtn")
        self.startListenBtn = QtWidgets.QPushButton(self.centralwidget)
        self.startListenBtn.setEnabled(True)
        self.startListenBtn.setGeometry(QtCore.QRect(20, 140, 271, 51))
        self.startListenBtn.setAutoDefault(False)
        self.startListenBtn.setDefault(False)
        self.startListenBtn.setFlat(False)
        self.startListenBtn.setObjectName("startListenBtn")
        self.showResBtn = QtWidgets.QPushButton(self.centralwidget)
        self.showResBtn.setGeometry(QtCore.QRect(340, 450, 271, 51))
        self.showResBtn.setObjectName("showResBtn")
        self.recBtn = QtWidgets.QPushButton(self.centralwidget)
        self.recBtn.setGeometry(QtCore.QRect(330, 140, 51, 51))
        self.recBtn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./buttons_py/rec_but.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.recBtn.setIcon(icon)
        self.recBtn.setIconSize(QtCore.QSize(51, 51))
        self.recBtn.setFlat(True)
        self.recBtn.setObjectName("recBtn")
        self.pauseBtn = QtWidgets.QPushButton(self.centralwidget)
        self.pauseBtn.setGeometry(QtCore.QRect(390, 140, 51, 51))
        self.pauseBtn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("./buttons_py/pause_but.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pauseBtn.setIcon(icon1)
        self.pauseBtn.setIconSize(QtCore.QSize(51, 51))
        self.pauseBtn.setFlat(True)
        self.pauseBtn.setObjectName("pauseBtn")
        self.playBtn = QtWidgets.QPushButton(self.centralwidget)
        self.playBtn.setGeometry(QtCore.QRect(450, 140, 51, 51))
        self.playBtn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("./buttons_py/play_but.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.playBtn.setIcon(icon2)
        self.playBtn.setIconSize(QtCore.QSize(51, 51))
        self.playBtn.setFlat(True)
        self.playBtn.setObjectName("playBtn")
        self.stopBtn = QtWidgets.QPushButton(self.centralwidget)
        self.stopBtn.setGeometry(QtCore.QRect(510, 140, 51, 51))
        self.stopBtn.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("./buttons_py/stop_but.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.stopBtn.setIcon(icon3)
        self.stopBtn.setIconSize(QtCore.QSize(51, 51))
        self.stopBtn.setFlat(True)
        self.stopBtn.setObjectName("stopBtn")
        self.tEdit = QtWidgets.QTimeEdit(self.centralwidget)
        self.tEdit.setEnabled(True)
        self.tEdit.setGeometry(QtCore.QRect(580, 150, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setKerning(True)
        self.tEdit.setFont(font)
        self.tEdit.setWrapping(False)
        self.tEdit.setFrame(True)
        self.tEdit.setReadOnly(True)
        self.tEdit.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.tEdit.setAccelerated(False)
        self.tEdit.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToPreviousValue)
        self.tEdit.setKeyboardTracking(True)
        self.tEdit.setTimeSpec(QtCore.Qt.TimeZone)
        self.tEdit.setObjectName("tEdit")
        self.cmb = QtWidgets.QComboBox(self.centralwidget)
        self.cmb.setGeometry(QtCore.QRect(300, 155, 631, 36))
        self.cmb.setAccessibleName("")
        self.cmb.setAutoFillBackground(True)
        self.cmb.setEditable(False)
        self.cmb.setPlaceholderText("")
        self.cmb.setObjectName("cmb")
        self.cmb.addItem("")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.loadBtn.setText(_translate("MainWindow", "Загрузить стих"))
        self.startListenBtn.setText(_translate("MainWindow", "Начать прослушивание"))
        self.showResBtn.setText(_translate("MainWindow", "Проверить результат"))
        self.tEdit.setDisplayFormat(_translate("MainWindow", "hh.mm.ss"))
        self.cmb.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.cmb.setCurrentText(_translate("MainWindow", "Выберите аудиоустройство для записи"))
        self.cmb.setItemText(0, _translate("MainWindow", "Выберите аудиоустройство для записи"))
